epoch: 50
test_epoch: 5

parallel_part:
  - emb_func

pretrain_path: ./pth/Baseline-20240106T180818Z-001/Baseline/Baseline-miniImageNet--ravi-resnet18-5-Reproduce/checkpoints/model_best.pth
resume: False
# few shot settings
way_num: 5
shot_num: 5
query_num: 11
test_way: ~ # use ~ -> test_* = *_num
test_shot: ~
test_query: ~
episode_size: 1
train_episode: 100
test_episode: 100

# general model setting
batch_size: 128
val_per_epoch: 1
